{% set name = "h3" %}
{% set version = "3.6.1" %}

package:
  name: {{ name|lower }}-py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6cc063403ef8b0c97888ff6131bb7791b15b2fb70954588d3e30f230b1ab03c5
  patches:
    # patch to override setup.py and h3.py to load dynamic libraries from conda distribution of H3
    - load_from_dynamic_libraries.patch

build:
  number: 0
  skip: true  # [(win and vc<14) or py27]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - h3
  run:
    - python
    - h3

test:
  commands:
    - python -c "from h3 import h3"

about:
  home: https://github.com/uber/h3-py.git
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Python bindings for H3, a hierarchical hexagonal geospatial indexing system developed by Uber Technologies
  dev_url: https://github.com/uber/h3-py.git

extra:
  recipe-maintainers:
    - benhuff
    - oblute
    - geoHeil
